baseURL = "https://mscazmy.github.io/"
languageCode = "en-us"
title = "Ahmed Azeez | Portfolio"
theme = "data-science"
enableEmoji = true
enableRobotsTXT = true

preserveTaxonomyNames = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[params]
  author = "Ahmed Azeez"
  description = "A PhD in Public Health with a passion for data analysis and infectious disease epidemiology — transforming evidence into insight for healthier communities."
  # Updated social metadata
  twitterAuthor = ""
  twitterSite = ""
  images = ['logo.jpg']

  # Syntax highlighting options
  highlight = true
  highlightjsVersion = "9.15.6"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml", "javascript", "python"]
  custom = true
  highlightjsThemeLight = ""
  highlightjsThemeDark = ""

[params.social]
  email = "mailto:ahmed.azeez1987@gmail.com"
  github = "https://github.com/mscazmy"
  linkedin = "https://www.linkedin.com/in/ahmed-a-hasan-%F0%9F%87%AE%F0%9F%87%B6-070b9aab/"
  facebook = "https://www.facebook.com/ahmed.medic.583"
  twitter = ""
  stackoverflow = ""
  instagram = "https://www.instagram.com/msc_az?igsh=ZmY4cHhrZHFxbzcx"
  dribbble = ""
  kaggle = ""
  medium = ""
  patreon = ""
  pinterest = "https://www.pinterest.com/ahmedazeez1987/"
  youtube = ""
