
<!DOCTYPE html>
<html lang="en-US">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:image" content="https://mscazmy.github.io/2016/11/10/bicyclesseattle/thumbnail.jpg" /><meta name="twitter:title" content="Bicycle Sharing in Seattle"/>
<meta name="twitter:description" content="Exploring the usage of Pronto! ridesharing bikes in Seattle"/>

  <meta property="og:title" content="Bicycle Sharing in Seattle" />
<meta property="og:description" content="Exploring the usage of Pronto! ridesharing bikes in Seattle" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://mscazmy.github.io/2016/11/10/bicyclesseattle/" /><meta property="og:image" content="https://mscazmy.github.io/2016/11/10/bicyclesseattle/thumbnail.jpg" /><meta property="article:section" content="post" />
<meta property="article:published_time" content="2016-11-10T00:00:00+00:00" />
<meta property="article:modified_time" content="2016-11-10T00:00:00+00:00" />


  
  <title>Bicycle Sharing in Seattle | Ahmed Azeez</title>
  
  <link rel="stylesheet" type="text/css" href="/css/style.css">
  <link rel="stylesheet" type="text/css" href="/css/variables.css">
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans|Merriweather:300,700|Noto+Sans:400,700" rel="stylesheet">

 

  
    
    
    
    
    
      <link rel="stylesheet" type="text/css" href="/css/custom-light-syntax.css" id="syntaxLight">
      <link rel="stylesheet alternate" type="text/css" href="/css/custom-dark-syntax.css" id="syntaxDark">
    

  

</head>


<main>

  
  <div class='post-background'>
    <div class='post-gradient'></div>

    
<nav class="nav__simple">
  <div class="nav__content">
    <div class="goHome">
      <a href="/" aria-label="Go back to all posts"><span class="inline-svg inline-svg-arrow-left" >
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M257.5 445.1l-22.2 22.2c-9.4 9.4-24.6 9.4-33.9 0L7 273c-9.4-9.4-9.4-24.6 0-33.9L201.4 44.7c9.4-9.4 24.6-9.4 33.9 0l22.2 22.2c9.5 9.5 9.3 25-.4 34.3L136.6 216H424c13.3 0 24 10.7 24 24v32c0 13.3-10.7 24-24 24H136.6l120.5 114.8c9.8 9.3 10 24.8.4 34.3z"/></svg>

</span>
 <span class='scroll-text'>Back to All</span></a>
    </div>

    <p class="nav__title">Ahmed Azeez </p>

    <div class='toggle-container'>
      <button class="theme-toggle">
        <span class="scroll-text theme-text">Enable Dark Mode</span>
        <div class="single-toggle">
          <span class="inline-svg inline-svg-moon" >
<!-- <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M279.135 512c78.756 0 150.982-35.804 198.844-94.775 28.27-34.831-2.558-85.722-46.249-77.401-82.348 15.683-158.272-47.268-158.272-130.792 0-48.424 26.06-92.292 67.434-115.836 38.745-22.05 28.999-80.788-15.022-88.919A257.936 257.936 0 0 0 279.135 0c-141.36 0-256 114.575-256 256 0 141.36 114.576 256 256 256zm0-464c12.985 0 25.689 1.201 38.016 3.478-54.76 31.163-91.693 90.042-91.693 157.554 0 113.848 103.641 199.2 215.252 177.944C402.574 433.964 344.366 464 279.135 464c-114.875 0-208-93.125-208-208s93.125-208 208-208z"/></svg> -->

<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 48 48'><path fill="currentColor" d='M33.3 33.2c-5.1 5.1-13.3 5.1-18.4 0s-5.1-13.3 0-18.4c1.3-1.3 3-2.4 4.9-3 .6-.2 1.3-.1 1.7.4.4.4.6 1.1.4 1.7-1.3 3.6-.4 7.5 2.3 10.2s6.6 3.5 10.2 2.3c.6-.2 1.2-.1 1.7.4.4.4.6 1.1.4 1.7-.8 1.8-1.9 3.4-3.2 4.7zm-16.1-2.3c4.1 4.1 11 3.7 14.6-.8-3.7.2-7.3-1.1-9.9-3.8-2.7-2.7-4-6.3-3.8-9.9-4.4 3.3-5.1 10.1-.9 14.5z' fill='#FFF'/></svg>

</span>

          <span class="inline-svg inline-svg-sun" >
<!-- <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm0 448c-110.5 0-200-89.5-200-200S145.5 56 256 56s200 89.5 200 200-89.5 200-200 200z"/></svg> -->
<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 48 48'><path fill="currentColor" d='M24 15.2c-4.9 0-8.9 4-8.9 8.9s4 8.9 8.9 8.9 8.9-4 8.9-8.9-4-8.9-8.9-8.9zm0 14.1c-2.9 0-5.2-2.3-5.2-5.2 0-2.9 2.3-5.2 5.2-5.2s5.2 2.3 5.2 5.2c0 2.9-2.3 5.2-5.2 5.2zM24 13.5c1 0 1.8-.8 1.8-1.8V7.9c0-1-.8-1.8-1.8-1.8s-1.8.8-1.8 1.8v3.7c0 1.1.8 1.9 1.8 1.9zM24 34.7c-1 0-1.8.8-1.8 1.8v3.7c0 1 .8 1.8 1.8 1.8s1.8-.8 1.8-1.8v-3.7c0-1-.8-1.8-1.8-1.8zM34.4 16.4l2.6-2.7c.7-.7.7-1.9 0-2.6-.7-.7-1.9-.7-2.6 0l-2.6 2.6c-.7.7-.7 1.9 0 2.6.7.8 1.8.8 2.6.1zM13.6 31.8L11 34.5c-.7.7-.7 1.9 0 2.6s1.9.7 2.6 0l2.6-2.6c.7-.7.7-1.9 0-2.6-.7-.8-1.8-.8-2.6-.1zM13.4 24.1c0-1-.8-1.8-1.8-1.8H7.8c-1 0-1.8.8-1.8 1.8s.8 1.8 1.8 1.8h3.7c1.1 0 1.9-.8 1.9-1.8zM40.2 22.3h-3.7c-1 0-1.8.8-1.8 1.8s.8 1.8 1.8 1.8h3.7c1 0 1.8-.8 1.8-1.8s-.8-1.8-1.8-1.8zM13.6 16.4c.7.7 1.9.7 2.6 0 .7-.7.7-1.9 0-2.6l-2.6-2.7c-.7-.7-1.8-.7-2.6 0-.7.8-.7 1.9 0 2.6l2.6 2.7zM34.4 31.8c-.7-.7-1.9-.7-2.6 0-.7.7-.7 1.9 0 2.6l2.6 2.6c.7.7 1.9.7 2.6 0 .7-.7.7-1.9 0-2.6l-2.6-2.6z' fill='#FFF'/></svg>

</span>

        </div>
      </button>
    </div>
  </div>
</nav>

    


    <div class='container-toTop'>
      <div class='toTop-spacing'>
        <div class='toTop-hidden'></div>
        <a href="#" class="toTop is-hidden" aria-label="Scroll to top">
          <span class="inline-svg inline-svg-chevron-up" >
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M240.971 130.524l194.343 194.343c9.373 9.373 9.373 24.569 0 33.941l-22.667 22.667c-9.357 9.357-24.522 9.375-33.901.04L224 227.495 69.255 381.516c-9.379 9.335-24.544 9.317-33.901-.04l-22.667-22.667c-9.373-9.373-9.373-24.569 0-33.941L207.03 130.525c9.372-9.373 24.568-9.373 33.941-.001z"/></svg>

</span>

        </a>
      </div>
    </div>
  </div>

  <article class="article">

    <section class="post__info">
      
        <p class='item__meta-category single'>project</p>
      

      <h1 class="post__title">Bicycle Sharing in Seattle</h1>

      

      
      <div class='post__tags'>
        <p class='post__tags-meta'>Tags:</p>
        
            <button class='item__meta-tag post-tag' aria-label='Back to all posts filtered by maps'>maps</button>
        
            <button class='item__meta-tag post-tag' aria-label='Back to all posts filtered by data viz'>data viz</button>
        
            <button class='item__meta-tag post-tag' aria-label='Back to all posts filtered by R'>R</button>
        
      </div>
      

      
      <div class="post__date">
        <p>November 10 2016 • 28 min read</p>
      </div>
      

      
      <div class='post__authors'>
          
          <a href="" ref="author">
          
            <div class='post__author'>
              <img src="/images/logo.jpg" alt="" class='post__author-img'>
              <div class='post__author-social'>
                  <span class='post__author-name'>Ahmed Azeez</span>
                
                  <span class='post__author-website'>Website</span>
                
              </div>
            </div>
            </a>
          
        
      </div>
      

      
        <img class="post__image" src="bike2.jpg" alt="Orange and purple bike leaning against a white brick wall" class="img-responsive">
        
          <p class="post__image-credit">Image by <a href="https://unsplash.com/photos/0ClfreiNppM?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Tiffany Nutt</a>
            
          </p>
        
      


    </section>

    <section class="post__content">
      


<ul>
<li><a href="#introduction">Introduction</a></li>
<li><a href="#data-visualizations">Data Visualizations</a></li>
<li><a href="#conclusions">Conclusions</a></li>
</ul>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>This is an exploration of bicycle-sharing data in the city of Seattle, WA (USA) from October 2014 - August 2016. I hope to eventually combine this data with other forms of ride-sharing and transportation in the city, but this will be the first step.</p>
<p>Time to get started!</p>
<div id="loading-necessary-packages" class="section level3">
<h3>Loading Necessary Packages</h3>
<pre class="r"><code># For data manipulation and tidying
library(dplyr)
library(lubridate)
library(tidyr)

# For mapping
library(ggmap)
library(mapproj)

# For data visualizations
library(ggplot2)

# For modeling and machine learning
library(caret)</code></pre>
</div>
<div id="importing-data" class="section level3">
<h3>Importing Data</h3>
<p>All of the data can be downloaded from the bicycle-sharing service <a href="https://www.prontocycleshare.com/data">“Pronto!”’s website</a> or from <a href="https://www.kaggle.com/pronto/cycle-share-dataset">Kaggle</a>. This project contains 3 data sets and I’ll import and inspect each data file independently.</p>
<pre class="r"><code>station &lt;- read.csv(file = &quot;2016_station_data.csv&quot;, header = TRUE, 
    stringsAsFactors = FALSE)

trip &lt;- read.csv(file = &quot;2016_trip_data.csv&quot;, header = TRUE, 
    stringsAsFactors = FALSE)

weather &lt;- read.csv(file = &quot;2016_weather_data.csv&quot;, header = TRUE, 
    stringsAsFactors = FALSE)</code></pre>
<p>Ok, let’s take a look at each of these data files.</p>
<div id="data-structures-and-variables" class="section level4">
<h4>Data Structures and Variables</h4>
<div id="station" class="section level5">
<h5>Station</h5>
<pre><code>## Observations: 58
## Variables: 9
## $ station_id        &lt;chr&gt; &quot;BT-01&quot;, &quot;BT-03&quot;, &quot;BT-04&quot;, &quot;BT-05&quot;, &quot;CBD-03&quot;...
## $ name              &lt;chr&gt; &quot;3rd Ave &amp; Broad St&quot;, &quot;2nd Ave &amp; Vine St&quot;, &quot;...
## $ lat               &lt;dbl&gt; 47.61842, 47.61583, 47.61609, 47.61311, 47.6...
## $ long              &lt;dbl&gt; -122.3510, -122.3486, -122.3411, -122.3442, ...
## $ install_date      &lt;chr&gt; &quot;10/13/2014&quot;, &quot;10/13/2014&quot;, &quot;10/13/2014&quot;, &quot;1...
## $ install_dockcount &lt;int&gt; 18, 16, 16, 14, 20, 18, 20, 20, 20, 18, 16, ...
## $ modification_date &lt;chr&gt; &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;11/9/2015&quot;, &quot;&quot;,...
## $ current_dockcount &lt;int&gt; 18, 16, 16, 14, 20, 18, 20, 18, 20, 18, 0, 1...
## $ decommission_date &lt;chr&gt; &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;8/9...</code></pre>
<p>Looks like this dataset is dealing with 9 variables:</p>
<ul>
<li><strong>Station ID</strong> : The individual ID number for a bike station</li>
<li><strong>Name</strong> : The name of that station ID, also appears to be the rough location of the station</li>
<li><strong>Latitude</strong> : The latitude of the station</li>
<li><strong>Longitude</strong> : The longitude of the station</li>
<li><strong>Install Date</strong> : When that particular station was installed (in MM/DD/YYYY format)</li>
<li><strong>Install Dock Count</strong> : Number of docks (bike positions) available at each station on installation day</li>
<li><strong>Modification Date</strong> : When a particular station was modified (in MM/DD/YYYY format)</li>
<li><strong>Current Dock Count</strong> : Number of docks (bike positions) available at each station on August 31, 2016</li>
<li><strong>Decommission Date</strong> : The date that a particular station was put out of service (in MM/DD/YYYY format)</li>
</ul>
</div>
<div id="trip" class="section level5">
<h5>Trip</h5>
<pre><code>## Observations: 236,065
## Variables: 12
## $ trip_id           &lt;int&gt; 431, 432, 433, 434, 435, 436, 437, 438, 439,...
## $ starttime         &lt;chr&gt; &quot;10/13/2014 10:31&quot;, &quot;10/13/2014 10:32&quot;, &quot;10/...
## $ stoptime          &lt;chr&gt; &quot;10/13/2014 10:48&quot;, &quot;10/13/2014 10:48&quot;, &quot;10/...
## $ bikeid            &lt;chr&gt; &quot;SEA00298&quot;, &quot;SEA00195&quot;, &quot;SEA00486&quot;, &quot;SEA0033...
## $ tripduration      &lt;dbl&gt; 985.935, 926.375, 883.831, 865.937, 923.923,...
## $ from_station_name &lt;chr&gt; &quot;2nd Ave &amp; Spring St&quot;, &quot;2nd Ave &amp; Spring St&quot;...
## $ to_station_name   &lt;chr&gt; &quot;Occidental Park / Occidental Ave S &amp; S Wash...
## $ from_station_id   &lt;chr&gt; &quot;CBD-06&quot;, &quot;CBD-06&quot;, &quot;CBD-06&quot;, &quot;CBD-06&quot;, &quot;CBD...
## $ to_station_id     &lt;chr&gt; &quot;PS-04&quot;, &quot;PS-04&quot;, &quot;PS-04&quot;, &quot;PS-04&quot;, &quot;PS-04&quot;,...
## $ usertype          &lt;chr&gt; &quot;Member&quot;, &quot;Member&quot;, &quot;Member&quot;, &quot;Member&quot;, &quot;Mem...
## $ gender            &lt;chr&gt; &quot;Male&quot;, &quot;Male&quot;, &quot;Female&quot;, &quot;Female&quot;, &quot;Male&quot;, ...
## $ birthyear         &lt;int&gt; 1960, 1970, 1988, 1977, 1971, 1974, 1978, 19...</code></pre>
<p>This dataset appears to contain 12 variables:</p>
<ul>
<li><strong>Trip ID</strong> : An identification number assigned to each trip (from one bike station to another)</li>
<li><strong>Start Time</strong> : The time and date that a bike was borrowed from a station (in MM/DD/YYYY HH:MM format)</li>
<li><strong>Stop Time</strong> : The time and date that a bike was returned to a station (in MM/DD/YYYY HH:MM format)</li>
<li><strong>Bike ID</strong> : The identification number for a specific bike</li>
<li><strong>Trip Duration</strong> : Time of trip (measured in seconds)</li>
<li><strong>From Station Name</strong> : The name of the station where the bike was borrowed from</li>
<li><strong>To Station Name</strong> : The name of the station where the bike was returned to</li>
<li><strong>From Station ID</strong> : The ID number of the station where the bike was borrowed from</li>
<li><strong>To Station ID</strong> : The ID number of the station where the bike was returned to</li>
<li><strong>User Type</strong> : Indicates whether the user was a “Member” (i.e., someone with a monthly or annual membership to Pronto!) or a “Short-Term Pass Holder” (i.e., someone who purchased a 24 hour or 3 day pass)</li>
<li><strong>Gender</strong> : The gender of the rider (if known)</li>
<li><strong>Birth Year</strong> : The year that the rider was born</li>
</ul>
</div>
<div id="weather" class="section level5">
<h5>Weather</h5>
<pre><code>## Observations: 689
## Variables: 21
## $ Date                       &lt;chr&gt; &quot;10/13/2014&quot;, &quot;10/14/2014&quot;, &quot;10/15/...
## $ Max_Temperature_F          &lt;int&gt; 71, 63, 62, 71, 64, 68, 73, 66, 64,...
## $ Mean_Temperature_F         &lt;int&gt; 62, 59, 58, 61, 60, 64, 64, 60, 58,...
## $ Min_TemperatureF           &lt;int&gt; 54, 55, 54, 52, 57, 59, 55, 55, 55,...
## $ Max_Dew_Point_F            &lt;int&gt; 55, 52, 53, 49, 55, 59, 57, 57, 52,...
## $ MeanDew_Point_F            &lt;int&gt; 51, 51, 50, 46, 51, 57, 55, 54, 49,...
## $ Min_Dewpoint_F             &lt;int&gt; 46, 50, 46, 42, 41, 55, 53, 50, 46,...
## $ Max_Humidity               &lt;int&gt; 87, 88, 87, 83, 87, 90, 94, 90, 87,...
## $ Mean_Humidity              &lt;int&gt; 68, 78, 77, 61, 72, 83, 74, 78, 70,...
## $ Min_Humidity               &lt;int&gt; 46, 63, 67, 36, 46, 68, 52, 67, 58,...
## $ Max_Sea_Level_Pressure_In  &lt;dbl&gt; 30.03, 29.84, 29.98, 30.03, 29.83, ...
## $ Mean_Sea_Level_Pressure_In &lt;dbl&gt; 29.79, 29.75, 29.71, 29.95, 29.78, ...
## $ Min_Sea_Level_Pressure_In  &lt;dbl&gt; 29.65, 29.54, 29.51, 29.81, 29.73, ...
## $ Max_Visibility_Miles       &lt;int&gt; 10, 10, 10, 10, 10, 10, 10, 10, 10,...
## $ Mean_Visibility_Miles      &lt;int&gt; 10, 9, 9, 10, 10, 8, 10, 10, 10, 6,...
## $ Min_Visibility_Miles       &lt;int&gt; 4, 3, 3, 10, 6, 2, 6, 5, 6, 2, 10, ...
## $ Max_Wind_Speed_MPH         &lt;int&gt; 13, 10, 18, 9, 8, 10, 10, 12, 15, 1...
## $ Mean_Wind_Speed_MPH        &lt;int&gt; 4, 5, 7, 4, 3, 4, 3, 5, 8, 8, 9, 4,...
## $ Max_Gust_Speed_MPH         &lt;chr&gt; &quot;21&quot;, &quot;17&quot;, &quot;25&quot;, &quot;-&quot;, &quot;-&quot;, &quot;-&quot;, &quot;1...
## $ Precipitation_In           &lt;dbl&gt; 0.00, 0.11, 0.45, 0.00, 0.14, 0.31,...
## $ Events                     &lt;chr&gt; &quot;Rain&quot;, &quot;Rain&quot;, &quot;Rain&quot;, &quot;Rain&quot;, &quot;Ra...</code></pre>
<p>This dataset represents quite a bit of weather data in 21 variables.</p>
<ul>
<li><strong>Date</strong> : The date in MM/DD/YYYY format</li>
<li><strong>Max Temperature F</strong> : The maximum temperature that day (in degrees F)</li>
<li><strong>Mean Temperature F</strong> : The average temperature that day (in degrees F)</li>
<li><strong>Min Temperature F</strong> : The minimum temperature that day (in degrees F)</li>
<li><strong>Max Dew Point F</strong> : The maximum dew point (in degrees F)</li>
<li><strong>Mean Dew Point F</strong> : The average dew point (in degrees F)</li>
<li><strong>Min Dew Point F</strong> : The minimum dew point (in degrees F)</li>
<li><strong>Max Humidity</strong> : The maximum humidity (in %)</li>
<li><strong>Mean Humidity</strong> : The average humidity (in %)</li>
<li><strong>Min Humidity</strong> : The minimum humidity (in %)</li>
<li><strong>Maximum Sea Level Pressure</strong> : The maximum atmospheric pressure at sea level (in inches of mercury)</li>
<li><strong>Mean Sea Level Pressure</strong> : The average atmospheric pressure at sea level (in inches of mercury)</li>
<li><strong>Min Sea Level Pressure</strong> : The minimum atmospheric pressure at sea level (in inches of mercury)</li>
<li><strong>Max Visibility Miles</strong> : The maximum visibility (in miles)</li>
<li><strong>Mean Visibility Miles</strong> : The average visibility (in miles)</li>
<li><strong>Min Visibility Miles</strong> : The minimum visibility (in miles)</li>
<li><strong>Max Wind Speed MPH</strong> : The maximum sustained wind speed (in miles per hour)</li>
<li><strong>Mean Wind Speed MPH</strong> : The average sustained wind speed (in miles per hour)</li>
<li><strong>Max Gust Speed MPH</strong> : The maximum gust wind speed (in miles per hour)</li>
<li><strong>Precipitation</strong> : The amount of precipitation (measured in inches)</li>
<li><strong>Events</strong> : Weather events that occurred that day (e.g., rain, fog, snow, thunderstorm etc.)</li>
</ul>
</div>
</div>
</div>
</div>
<div id="data-visualizations" class="section level2">
<h2>Data Visualizations</h2>
<div id="exploring-the-stations-dataset" class="section level3">
<h3>Exploring the Stations Dataset</h3>
<p>Since the “Stations” dataset was the first one I imported, let’s start with a little exploration there. First of all, how many unique stations are we dealing with?</p>
<pre class="r"><code>station %&gt;% summarise(n_distinct(station_id))</code></pre>
<pre><code>##   n_distinct(station_id)
## 1                     58</code></pre>
<p>Wow! 58 different stations! Let’s take a quick peek at where they are located.</p>
<pre class="r"><code>station_locs &lt;- station %&gt;% group_by(station_id) %&gt;% select(1:4, 
    -2)</code></pre>
<pre class="r"><code># Load the correct map
mymap &lt;- get_map(location = &quot;Seattle&quot;, maptype = &quot;roadmap&quot;, zoom = 12)

# Plot a single point for each Station ID
ggmap(mymap) + geom_point(aes(x = long, y = lat), data = station_locs, 
    alpha = 0.7, color = &quot;darkred&quot;, size = 2)</code></pre>
<div class="float">
<img src="unnamed-chunk-8-1.png" alt="Zoomed out map of Seattle showing red dots around downtown and university district" />
<div class="figcaption">Zoomed out map of Seattle showing red dots around downtown and university district</div>
</div>
<p>So it looks like all of the stations are located near the Lower Queen Anne, Belltown, International District, Capitol Hill and University of Washington areas. Let’s take a more zoomed-in look.</p>
<div class="float">
<img src="unnamed-chunk-9-1.png" alt="Zoomed in map of Seattle showing red dots around downtown and university district" />
<div class="figcaption">Zoomed in map of Seattle showing red dots around downtown and university district</div>
</div>
<p>Great! So the locations are pretty well clustered. I wonder what order they were added in.</p>
<div id="station-installations" class="section level4">
<h4>Station Installations</h4>
<p>First, let’s convert those character-string date objects to actual dates using the <code>lubridate</code> package.</p>
<pre class="r"><code>station$install_date &lt;- mdy(station$install_date)</code></pre>
<pre class="r"><code># How many times were new stations installed?
station %&gt;% summarise(n_distinct(install_date))</code></pre>
<pre><code>##   n_distinct(install_date)
## 1                        9</code></pre>
<pre class="r"><code># How many stations were installed on each date?
station %&gt;% group_by(install_date) %&gt;% summarise(count = n()) %&gt;% 
    arrange(install_date)</code></pre>
<pre><code>## # A tibble: 9 × 2
##   install_date count
##         &lt;date&gt; &lt;int&gt;
## 1   2014-10-13    50
## 2   2015-05-22     1
## 3   2015-06-12     1
## 4   2015-07-27     1
## 5   2015-09-15     1
## 6   2015-10-29     1
## 7   2016-03-18     1
## 8   2016-07-03     1
## 9   2016-08-09     1</code></pre>
<p>It looks like the vast majority (86%) of the stations were added on opening day. Let’s see where those original ones were and where the rest were added.</p>
<p><img src="unnamed-chunk-12-1.png" alt="Zoomed in map of Seattle showing red dots in the original locations of the bike stations - mostly around downtown and university district" />
<img src="unnamed-chunk-12-2.png" alt="Zoomed in map of Seattle showing various color dots, each color representing the date that each station was added to the network." /></p>
<p>So they added more stations throughout the district that they serve, instead of adding several new stations to a single neighborhood all at once. Good to know.</p>
<p>Now, I wonder how many bikes can be parked at each station (as of August 31,2016)?</p>
<div class="float">
<img src="unnamed-chunk-13-1.png" alt="Bar graph showing that most bike stations currently house between 13 an 20 bikes." />
<div class="figcaption">Bar graph showing that most bike stations currently house between 13 an 20 bikes.</div>
</div>
<p>Well that’s weird, some of the stations have a dock count of 0. I’m assuming they didn’t start that way. Let’s calculate the change in dock count from station installation to August 31, 2016 and plot it on a map.</p>
<pre class="r"><code>dock_change &lt;- station %&gt;% group_by(station_id) %&gt;% select(station_id, 
    long, lat, ends_with(&quot;dockcount&quot;)) %&gt;% mutate(dock_change = current_dockcount - 
    install_dockcount)</code></pre>
<div id="change-in-number-of-bike-docks-per-station" class="section level5">
<h5>Change in Number of Bike Docks Per Station</h5>
<p>Any stations with no change in number of docks are not shown here.</p>
<div class="float">
<img src="unnamed-chunk-15-1.png" alt="Map of Seattle with different sized and colored dots showing the amount of bikes that have been added or removed from docking stations. Most stations have lost bikes." />
<div class="figcaption">Map of Seattle with different sized and colored dots showing the amount of bikes that have been added or removed from docking stations. Most stations have lost bikes.</div>
</div>
<p>Wow! Looks like quite a few stations took away bike docks and none gained any. Perhaps those stations weren’t being used very frequently. We’ll have to look at that a bit later.</p>
</div>
</div>
<div id="current-station-size" class="section level4">
<h4>Current Station Size</h4>
<p>I’m going to take one quick look at the current size of each station before moving on to the next dataset. <em>Note: I did not include any stations that were closed as of August 31, 2016 in this map</em></p>
<div class="float">
<img src="unnamed-chunk-16-1.png" alt="Zoomed in map of Seattle with various size dots showing the current station size of all bike stations." />
<div class="figcaption">Zoomed in map of Seattle with various size dots showing the current station size of all bike stations.</div>
</div>
<p>So it looks like the biggest stations tend to be on the outskirts of the rest. Where there are several stations in close proximity, there tend to be fewer bike docks at each station. That makes sense, logically speaking. If you go to a station and there is no bike to rent, you can easily go to another nearby, assuming there is another nearby. In areas where the stations are more secluded, it’s more important that there be bikes and open spaces readily available for users.</p>
<p>Alright, I’m feeling good about exploring this dataset. Time to check out the trip dataset!</p>
</div>
</div>
<div id="exploring-the-trips-dataset" class="section level3">
<h3>Exploring the Trips Dataset</h3>
<p>It’s been a while since we’ve looked at the trip dataset, so let’s take another peek at it here.</p>
<pre><code>## Observations: 236,065
## Variables: 12
## $ trip_id           &lt;int&gt; 431, 432, 433, 434, 435, 436, 437, 438, 439,...
## $ starttime         &lt;chr&gt; &quot;10/13/2014 10:31&quot;, &quot;10/13/2014 10:32&quot;, &quot;10/...
## $ stoptime          &lt;chr&gt; &quot;10/13/2014 10:48&quot;, &quot;10/13/2014 10:48&quot;, &quot;10/...
## $ bikeid            &lt;chr&gt; &quot;SEA00298&quot;, &quot;SEA00195&quot;, &quot;SEA00486&quot;, &quot;SEA0033...
## $ tripduration      &lt;dbl&gt; 985.935, 926.375, 883.831, 865.937, 923.923,...
## $ from_station_name &lt;chr&gt; &quot;2nd Ave &amp; Spring St&quot;, &quot;2nd Ave &amp; Spring St&quot;...
## $ to_station_name   &lt;chr&gt; &quot;Occidental Park / Occidental Ave S &amp; S Wash...
## $ from_station_id   &lt;chr&gt; &quot;CBD-06&quot;, &quot;CBD-06&quot;, &quot;CBD-06&quot;, &quot;CBD-06&quot;, &quot;CBD...
## $ to_station_id     &lt;chr&gt; &quot;PS-04&quot;, &quot;PS-04&quot;, &quot;PS-04&quot;, &quot;PS-04&quot;, &quot;PS-04&quot;,...
## $ usertype          &lt;chr&gt; &quot;Member&quot;, &quot;Member&quot;, &quot;Member&quot;, &quot;Member&quot;, &quot;Mem...
## $ gender            &lt;chr&gt; &quot;Male&quot;, &quot;Male&quot;, &quot;Female&quot;, &quot;Female&quot;, &quot;Male&quot;, ...
## $ birthyear         &lt;int&gt; 1960, 1970, 1988, 1977, 1971, 1974, 1978, 19...</code></pre>
<p>Great, so there are quite a few things that we can potentially look at using this dataset by itself. Let’s start with the number of trips per day since Pronto! began opening bike stations. To do that, we need to recode our start date/times as POSIXct objects. We’ll use the <code>lubridate</code> package for this.</p>
<pre class="r"><code># Make the start and stop dates into POSIXct objects
trip_2 &lt;- trip %&gt;% mutate(start_dt = mdy_hm(starttime), stop_dt = mdy_hm(stoptime))

# Recode the dates
trip_2 &lt;- trip_2 %&gt;% mutate(start_date = paste(month(start_dt), 
    day(start_dt), year(start_dt), sep = &quot;/&quot;))
trip_2$start_date &lt;- mdy(trip_2$start_date)

trip_2 &lt;- trip_2 %&gt;% mutate(stop_date = paste(month(stop_dt), 
    day(stop_dt), year(stop_dt), sep = &quot;/&quot;))
trip_2$stop_date &lt;- mdy(trip_2$stop_date)</code></pre>
<p>Great! Time to visualize the number of rides per day.</p>
<div class="float">
<img src="unnamed-chunk-19-1.png" alt="line graph showing daily fluctuations in the number of trips made per day." />
<div class="figcaption">line graph showing daily fluctuations in the number of trips made per day.</div>
</div>
<p>Hmm, grouping by day is a little noisy. Perhaps we should try by month?</p>
<div id="plotting-trips-per-month-by-season" class="section level4">
<h4>Plotting Trips Per Month (By Season)</h4>
<p>First, we need to create a “Year-Month” variable</p>
<pre class="r"><code>start_date_ym &lt;- trip_2 %&gt;% mutate(ym = paste(year(start_date), 
    month(start_date), sep = &quot;/&quot;))</code></pre>
<p>Now plot. I think I’ll plot this by month but color it by season (where December, January, and February are “winter”, March, April, and May are “spring”, June, July, August are “summer”, and September, October, November are “autumn”)</p>
<div class="float">
<img src="unnamed-chunk-21-1.png" alt="Line graph showing the number of trips taken per month over the course of the year and colored by season. Trips are highest in the summer, lowest in the winter." />
<div class="figcaption">Line graph showing the number of trips taken per month over the course of the year and colored by season. Trips are highest in the summer, lowest in the winter.</div>
</div>
<p>Well that intuitively makes sense. The number of trips taken per month increases in the spring, reaches a maximum in the summer, declines through the fall, remains fairly stable in the winter and then repeats.</p>
</div>
<div id="average-trip-duration" class="section level4">
<h4>Average Trip Duration</h4>
<p>Great! I wonder how the average trip duration fluctuates over this time period.</p>
<pre class="r"><code># Convert Trip Duration from Seconds to Minutes
Trip_Duration_Month &lt;- start_date_ym %&gt;% mutate(trip_duration_min = tripduration/60) %&gt;% 
    group_by(ym) %&gt;% select(ym, trip_duration_min) %&gt;% summarise(Avg = mean(trip_duration_min), 
    sd = sd(trip_duration_min)) %&gt;% mutate(se = sd/sqrt(n()))</code></pre>
<p>Now to plot the average trip duration (in minutes) (plus or minus standard error), with colors indicating season.</p>
<div class="float">
<img src="unnamed-chunk-23-1.png" alt="A line graph showing the duration (with standard error error bars) of the average trip per month, colored for each season. Trip durations peak in the summer and are low in the winter." />
<div class="figcaption">A line graph showing the duration (with standard error error bars) of the average trip per month, colored for each season. Trip durations peak in the summer and are low in the winter.</div>
</div>
<p>There’s surprisingly not a huge range in trip durations here.</p>
<p>The little bit of variation here makes logical sense. Longer trips were being taken in the spring and summer months rather than the fall and winter. It’s also notable that the spring and summer of 2016 may have shown fewer trips than the previous year, show a slight increase in average trip length.</p>
</div>
<div id="number-of-trips-by-day-of-week" class="section level4">
<h4>Number of Trips by Day of Week</h4>
<p>I wonder if people are using this service to commute to/from work. Let’s look at the number of trips by day of the week.</p>
<p>First, let’s create a Day of the Week variable.</p>
<pre class="r"><code>trip_2$wd &lt;- wday(trip_2$start_date, label = TRUE)</code></pre>
<p>Now to plot the total number of trips by day of the week.</p>
<div class="float">
<img src="unnamed-chunk-25-1.png" alt="A line graph showing number of trips taken by day of the week. There are slightly more trips taken Monday - Friday." />
<div class="figcaption">A line graph showing number of trips taken by day of the week. There are slightly more trips taken Monday - Friday.</div>
</div>
<p>Ok, so there are definitely more trips during the week than on the weekends. I wonder if this varies by season too.</p>
<div class="float">
<img src="unnamed-chunk-26-1.png" alt="Line graph with a line for each season showing the number of trips taken by day of the week. The lines are all pretty consistent within a season, and summer has the highest of all seasons." />
<div class="figcaption">Line graph with a line for each season showing the number of trips taken by day of the week. The lines are all pretty consistent within a season, and summer has the highest of all seasons.</div>
</div>
<p>So it looks like usage is relatively consistent across seasons, at least as far as the number of trips are concerned.</p>
</div>
<div id="number-of-trips-by-time-of-day" class="section level4">
<h4>Number of Trips by Time of Day</h4>
<p>How about time of day? Are people using these around commuting times during the week and later on weekends?</p>
<div class="float">
<img src="unnamed-chunk-27-1.png" alt="Seven, side-by-side graphs one for each day of the week. Each has a separate line for each of the four seasons, showing activity by hour of the day. Weekdays have spikes during rush hour and weekends are consistent throughout the day." />
<div class="figcaption">Seven, side-by-side graphs one for each day of the week. Each has a separate line for each of the four seasons, showing activity by hour of the day. Weekdays have spikes during rush hour and weekends are consistent throughout the day.</div>
</div>
<p>Wow, looks like regardless of the season, people are commuting to/from work using this service (there’s a spike between 8 and 10 AM and another between 4 and 7 PM Monday through Friday). But the weekends seem to be popular between 10 AM and 10 PM.</p>
</div>
<div id="number-of-trips-by-member-type" class="section level4">
<h4>Number of Trips by Member Type</h4>
<p>I wonder if different types of members (those who have a membership vs. those that bought a 24 hour or 3 day pass) vary in the number of trips they take.</p>
<p>If I were to guess, I’d think the short-term passes would be ideal for tourists or people looking for a quick weekend trip, whereas members may be more likely to continue using the service year-round. Let’s check out my assumptions by plotting, once again colored by season.</p>
<div class="float">
<img src="unnamed-chunk-28-1.png" alt="Line graph with 2 lines, one showing the number of trips per month, colored by season, for members, and one showing the number of trips per month, colored by season, for pass holders. The shape is similar, but passholders take fewer trips every month, especially in winter." />
<div class="figcaption">Line graph with 2 lines, one showing the number of trips per month, colored by season, for members, and one showing the number of trips per month, colored by season, for pass holders. The shape is similar, but passholders take fewer trips every month, especially in winter.</div>
</div>
<p>Surprisingly (to me, at least), different types of users seem to follow similar patterns of usage. Spring and Summer are definitely the most popular times for anyone to ride a bike in the Seattle area.</p>
</div>
<div id="trip-duration-by-member-type" class="section level4">
<h4>Trip Duration by Member Type</h4>
<p>While it may seem that the trip duration shouldn’t vary widely by member type, a quick look at <a href="https://www.prontocycleshare.com/pricing">Pronto!’s pricing structure</a> may make you reconsider that assumption. You see, while you have to purchase either an annual membership ($85/year), a 24-Hour Pass ($8) or a 3-Day Pass ($16) there is still a cap on the duration of your trip. For members, any ride under 45 minutes is free, but any ride going over 45 minutes will incur a fee of $2 for every additional 30 minutes. For short-term users, any ride under 30 minutes is free, but going over that time limit would cost you an additional $2 for the first 30 minutes and $5 for each additional 30 minutes after that!</p>
<p>Let’s see if these time limits cause differing behaviors in our users.</p>
<div class="float">
<img src="unnamed-chunk-29-1.png" alt="Two side-by-side histograms, showing member and short term pass holder trip duration with a black dotted line indicating the time when fees start accruing. Pass holers take a wider range of trip lengths and pay more fees." />
<div class="figcaption">Two side-by-side histograms, showing member and short term pass holder trip duration with a black dotted line indicating the time when fees start accruing. Pass holers take a wider range of trip lengths and pay more fees.</div>
</div>
<p>Ok, so our members are pretty good about making sure that they return their bike before they incur extra charges, but the short-term pass holders frequently go over their time limit. I wonder how the cost of a trip varies for members and pass holders. Let’s try to calculate the cost of a trip.</p>
<pre class="r"><code>trip_cost &lt;- trip_2 %&gt;% mutate(cost = ifelse(usertype == &quot;Member&quot; &amp; 
    tripduration_m &lt;= 45, 0, ifelse(usertype == &quot;Member&quot; &amp; tripduration_m &gt; 
    45 &amp; tripduration_m &lt;= 75, 2, ifelse(usertype == &quot;Member&quot; &amp; 
    tripduration_m &gt; 75, (2 + 5 * ((tripduration_m - 75)/30)), 
    ifelse(usertype == &quot;Short-Term Pass Holder&quot; &amp; tripduration_m &lt;= 
        30, 0, ifelse(usertype == &quot;Short-Term Pass Holder&quot; &amp; 
        tripduration_m &gt; 30 &amp; tripduration_m &lt; 60, 2, ifelse(usertype == 
        &quot;Short-Term Pass Holder&quot; &amp; tripduration_m &gt; 60, (2 + 
        5 * ((tripduration_m - 60)/30)), &quot;unknown&quot;)))))))</code></pre>
<p>That was a complicated nested if/else statement! Let’s see how much these folks are paying in additional fees!</p>
<div class="float">
<img src="unnamed-chunk-31-1.png" alt="Two bar graphs side by side, showing member and short-term pass holder fee paying behavior. Short-term pass holders pay more fees." />
<div class="figcaption">Two bar graphs side by side, showing member and short-term pass holder fee paying behavior. Short-term pass holders pay more fees.</div>
</div>
<p>Looks like short-term pass holders (who are already paying a higher price per day of biking), are also paying lots of extra fees. This could be because they are unfamiliar with the pricing structure and don’t realize they need to return their bike to a station within 30 minutes without getting charged. It is also possible that short-term users may be tourists who don’t know their way around as easily, and thus can’t find their way to a station within the time limit.</p>
</div>
<div id="member-demographics" class="section level4">
<h4>Member Demographics</h4>
<p>We only seem to have age and gender information about people who have an annual Pronto! membership, so we can at least take a look at what types of people use this service.</p>
<p>Let’s look first at age.</p>
<pre class="r"><code>trip_2$usertype &lt;- as.factor(trip_2$usertype)
trip_age &lt;- trip_2 %&gt;% mutate(age = year(start_dt) - birthyear)

hist(trip_age$age, main = &quot;Member Age&quot;, xlab = &quot;Number of Riders&quot;, 
    col = &quot;#56B4E9&quot;, breaks = 25)</code></pre>
<div class="float">
<img src="unnamed-chunk-32-1.png" alt="Histogram showing that the most riders are in their late 20s to early 30s." />
<div class="figcaption">Histogram showing that the most riders are in their late 20s to early 30s.</div>
</div>
<p>My first instinct here is to say “Wow! There’s a lot of 20 and 30-somethings that use this service!” But this figure (and these data) may be a little misleading. You see, we don’t have any sort of Rider ID number, meaning we can’t take “individual activity level” into account. So we can’t tell if the tallest spike is because 5 very athletic 28-year-olds went on 4,000 trips each, or if 100 people went on 200 trips each, or if there were 20,000 28-year-olds who each only used the service once.</p>
<p>The same problem would arise if we looked at gender, so I’m just going to move beyond demographics.</p>
</div>
<div id="trip-routes" class="section level4">
<h4>Trip Routes</h4>
<p>I’m going to do my best to look at some potential routes that these users could have taken, given their start and stop locations and duration. All of these data will be analyzed using the <code>ggmap</code> package and Google Maps API (<a href="https://journal.r-project.org/archive/2013-1/kahle-wickham.pdf">more info here</a>)</p>
<p>To start, I need to combine the coordinates of the station (from the <code>station</code> dataset) with the data from the <code>trip</code> dataset. Let’s get started.</p>
<pre class="r"><code># Create a dataframe with only station ID, latitude, and
# longitude
station_coord &lt;- station %&gt;% select(station_id, lat, long)

# Trim our trip dataframe to only include start &amp; stop
# dates/times, and station ID
trip_route &lt;- trip_2 %&gt;% select(trip_id, starts_with(&quot;start_&quot;), 
    starts_with(&quot;stop_&quot;), from_station_id, to_station_id, tripduration)

# Match by station ID
trip_route$start_lat &lt;- station_coord[match(trip_route$from_station_id, 
    station_coord$station_id), &quot;lat&quot;]

trip_route$start_long &lt;- station_coord[match(trip_route$from_station_id, 
    station_coord$station_id), &quot;long&quot;]

trip_route$stop_lat &lt;- station_coord[match(trip_route$to_station_id, 
    station_coord$station_id), &quot;lat&quot;]

trip_route$stop_long &lt;- station_coord[match(trip_route$to_station_id, 
    station_coord$station_id), &quot;long&quot;]</code></pre>
<p>Great! Now to start looking at routes.</p>
<p>I’ll start by looking at the possible routes of the very first trip.</p>
<div class="float">
<img src="unnamed-chunk-34-1.png" alt="Two side-by-side satellite images of Seattle, each showing a potential bike route from one place to another." />
<div class="figcaption">Two side-by-side satellite images of Seattle, each showing a potential bike route from one place to another.</div>
</div>
<p>Cool! So Google Maps API was able to give us two potential routes for this particular trip. We can make a best guess on which trip was taken by determining the trip duration.</p>
<pre class="r"><code># Converting trip duration to minutes
trip_route$tripduration &lt;- trip_route$tripduration/60

# Finding actual trip duration
trip_route[1, &quot;tripduration&quot;]</code></pre>
<pre><code>## [1] 16.43225</code></pre>
<p>Ok, so the actual trip on October 13, 2014 took 16.4 minutes. Let’s see how long each of the hypothetical trips took.</p>
<pre class="r"><code>leg_1 %&gt;% group_by(route) %&gt;% summarise(duration = sum(minutes))</code></pre>
<pre><code>## # A tibble: 2 × 2
##   route duration
##   &lt;chr&gt;    &lt;dbl&gt;
## 1     A 4.950000
## 2     B 5.583333</code></pre>
<p>Hmm, looks like Google estimates those trips should have only taken between 5 and 6 minutes. It is very possible that our user did not go directly from one station to the other. It’s also possible that he got stopped at a few red lights along his route.</p>
<p>Perhaps this, being the first trip, was a demo of some sort. Let’s check out the last trip that was recorded and see if we still run into the same time disconnect.</p>
<p><img src="unnamed-chunk-37-1.png" alt="Three side-by-side satellite images of Seattle, each showing a potential bike route from one place to another." />
Well this was certainly a longer ride than the first one we looked at!</p>
<p>How long did this trip take?</p>
<pre class="r"><code>trip_route[nrow(trip_route), &quot;tripduration&quot;]</code></pre>
<pre><code>## [1] 31.60052</code></pre>
<p>Ok, so how long did Google estimate it should take?</p>
<pre class="r"><code>leg_2 %&gt;% group_by(route) %&gt;% summarise(duration = sum(minutes))</code></pre>
<pre><code>## # A tibble: 3 × 2
##   route duration
##   &lt;chr&gt;    &lt;dbl&gt;
## 1     A  9.50000
## 2     B 12.13333
## 3     C 13.45000</code></pre>
<p>Once again, the trip took quite a bit longer than any of the routes shown here. It’s possible that estimating the routes taken by cyclists is not the best use of this dataset. So, what else is there to look at?</p>
</div>
<div id="station-by-trip-departure-and-arrival" class="section level4">
<h4>Station by Trip Departure and arrival</h4>
<p>I suppose we can see which stations have the most trip departures and which have the most arrivals. Unless people are always making round-trip journeys, these are not likely to be equal.</p>
</div>
<div id="station-usage" class="section level4">
<h4>Station Usage</h4>
<div id="trip-departure" class="section level5">
<h5>Trip Departure</h5>
<div class="float">
<img src="unnamed-chunk-40-1.png" alt="Zoomed in map of Seattle with different sized dots showing the departure of bikes. These are spread throughout the city." />
<div class="figcaption">Zoomed in map of Seattle with different sized dots showing the departure of bikes. These are spread throughout the city.</div>
</div>
</div>
<div id="trip-arrival" class="section level5">
<h5>Trip Arrival</h5>
<div class="float">
<img src="unnamed-chunk-41-1.png" alt="Zoomed in map of Seattle with different sized dots showing the arrival of bikes (or where they were returned at the end of a trip). Most of these are near the coast." />
<div class="figcaption">Zoomed in map of Seattle with different sized dots showing the arrival of bikes (or where they were returned at the end of a trip). Most of these are near the coast.</div>
</div>
<p>Great, so it looks like the station that sends the highest number of bikes out and takes the highest number of bikes in is located at Pier 69 / Alaskan Way &amp; Clay Street. Looks like this is pretty close to a few parks and several big tourist attractions.</p>
<p>Also, if you flip between “Departures” and “Arrivals”, you’ll notice that quite a few bikes are picked up in the Capitol Hill area, but are returned down by the coast. If you’re unfamiliar with Seattle’s topography, Capitol Hill is aptly named because it’s situated on a very steep hill. It makes sense that people would borrow bikes to ride <em>down</em> the hill, but not want to borrow a bike to go back <em>up</em> the hill. Interesting!</p>
</div>
</div>
</div>
<div id="exploring-the-weather-dataset" class="section level3">
<h3>Exploring the Weather Dataset</h3>
<p>Now that I’ve visualized all that I can think of in terms of the “trips” dataset, it’s time to take a brief look at the weather dataset.</p>
<p>Let’s get a quick reminder of what we’re looking at here.</p>
<pre class="r"><code>glimpse(weather)</code></pre>
<pre><code>## Observations: 689
## Variables: 21
## $ Date                       &lt;chr&gt; &quot;10/13/2014&quot;, &quot;10/14/2014&quot;, &quot;10/15/...
## $ Max_Temperature_F          &lt;int&gt; 71, 63, 62, 71, 64, 68, 73, 66, 64,...
## $ Mean_Temperature_F         &lt;int&gt; 62, 59, 58, 61, 60, 64, 64, 60, 58,...
## $ Min_TemperatureF           &lt;int&gt; 54, 55, 54, 52, 57, 59, 55, 55, 55,...
## $ Max_Dew_Point_F            &lt;int&gt; 55, 52, 53, 49, 55, 59, 57, 57, 52,...
## $ MeanDew_Point_F            &lt;int&gt; 51, 51, 50, 46, 51, 57, 55, 54, 49,...
## $ Min_Dewpoint_F             &lt;int&gt; 46, 50, 46, 42, 41, 55, 53, 50, 46,...
## $ Max_Humidity               &lt;int&gt; 87, 88, 87, 83, 87, 90, 94, 90, 87,...
## $ Mean_Humidity              &lt;int&gt; 68, 78, 77, 61, 72, 83, 74, 78, 70,...
## $ Min_Humidity               &lt;int&gt; 46, 63, 67, 36, 46, 68, 52, 67, 58,...
## $ Max_Sea_Level_Pressure_In  &lt;dbl&gt; 30.03, 29.84, 29.98, 30.03, 29.83, ...
## $ Mean_Sea_Level_Pressure_In &lt;dbl&gt; 29.79, 29.75, 29.71, 29.95, 29.78, ...
## $ Min_Sea_Level_Pressure_In  &lt;dbl&gt; 29.65, 29.54, 29.51, 29.81, 29.73, ...
## $ Max_Visibility_Miles       &lt;int&gt; 10, 10, 10, 10, 10, 10, 10, 10, 10,...
## $ Mean_Visibility_Miles      &lt;int&gt; 10, 9, 9, 10, 10, 8, 10, 10, 10, 6,...
## $ Min_Visibility_Miles       &lt;int&gt; 4, 3, 3, 10, 6, 2, 6, 5, 6, 2, 10, ...
## $ Max_Wind_Speed_MPH         &lt;int&gt; 13, 10, 18, 9, 8, 10, 10, 12, 15, 1...
## $ Mean_Wind_Speed_MPH        &lt;int&gt; 4, 5, 7, 4, 3, 4, 3, 5, 8, 8, 9, 4,...
## $ Max_Gust_Speed_MPH         &lt;chr&gt; &quot;21&quot;, &quot;17&quot;, &quot;25&quot;, &quot;-&quot;, &quot;-&quot;, &quot;-&quot;, &quot;1...
## $ Precipitation_In           &lt;dbl&gt; 0.00, 0.11, 0.45, 0.00, 0.14, 0.31,...
## $ Events                     &lt;chr&gt; &quot;Rain&quot;, &quot;Rain&quot;, &quot;Rain&quot;, &quot;Rain&quot;, &quot;Ra...</code></pre>
<p>Great, let’s change the Date variable to a POSIXct object, and make the “Events” variable factors.</p>
<pre class="r"><code># Adjusting the Date Variable
weather$Date &lt;- mdy(weather$Date)

# Adjusting the Events Variable
weather$Events &lt;- as.factor(weather$Events)</code></pre>
<p>Great. Now how many weather events are there?</p>
<pre class="r"><code>levels(weather$Events)</code></pre>
<pre><code>##  [1] &quot;&quot;                    &quot;Fog&quot;                 &quot;Fog , Rain&quot;         
##  [4] &quot;Fog-Rain&quot;            &quot;Rain&quot;                &quot;Rain , Snow&quot;        
##  [7] &quot;Rain , Thunderstorm&quot; &quot;Rain-Snow&quot;           &quot;Rain-Thunderstorm&quot;  
## [10] &quot;Snow&quot;</code></pre>
<p>Wow! So mostly combinations of rain…</p>
<p>Let’s combine a few of these things that seem to represent the same event.</p>
<pre class="r"><code>weather$Events &lt;- gsub(&quot;Fog , Rain|Fog-Rain&quot;, &quot;Fog-Rain&quot;, weather$Events)
weather$Events &lt;- gsub(&quot;Rain , Snow|Rain-Snow&quot;, &quot;Rain-Snow&quot;, 
    weather$Events)
weather$Events &lt;- gsub(&quot;Rain , Thunderstorm|Rain-Thunderstorm&quot;, 
    &quot;Rain-TS&quot;, weather$Events)

weather$Events &lt;- as.factor(weather$Events)</code></pre>
<p>Where else does this dataset need to be cleaned up? Let’s look for any missing values.</p>
<pre class="r"><code>summary(weather)</code></pre>
<pre><code>##       Date            Max_Temperature_F Mean_Temperature_F
##  Min.   :2014-10-13   Min.   :39.00     Min.   :33.00     
##  1st Qu.:2015-04-03   1st Qu.:55.00     1st Qu.:48.00     
##  Median :2015-09-22   Median :63.00     Median :56.00     
##  Mean   :2015-09-22   Mean   :64.03     Mean   :56.58     
##  3rd Qu.:2016-03-12   3rd Qu.:73.00     3rd Qu.:65.00     
##  Max.   :2016-08-31   Max.   :98.00     Max.   :83.00     
##                                         NA&#39;s   :1         
##  Min_TemperatureF Max_Dew_Point_F MeanDew_Point_F Min_Dewpoint_F 
##  Min.   :23.00    Min.   :10.00   Min.   : 4.00   Min.   : 1.00  
##  1st Qu.:43.00    1st Qu.:44.00   1st Qu.:41.00   1st Qu.:36.00  
##  Median :50.00    Median :50.00   Median :46.00   Median :42.00  
##  Mean   :49.45    Mean   :48.57   Mean   :45.02   Mean   :40.87  
##  3rd Qu.:57.00    3rd Qu.:54.00   3rd Qu.:51.00   3rd Qu.:47.00  
##  Max.   :70.00    Max.   :77.00   Max.   :59.00   Max.   :57.00  
##                                                                  
##   Max_Humidity    Mean_Humidity    Min_Humidity  
##  Min.   : 40.00   Min.   :24.00   Min.   :15.00  
##  1st Qu.: 78.00   1st Qu.:60.00   1st Qu.:38.00  
##  Median : 86.00   Median :70.00   Median :50.00  
##  Mean   : 84.54   Mean   :68.51   Mean   :49.97  
##  3rd Qu.: 90.00   3rd Qu.:79.00   3rd Qu.:63.00  
##  Max.   :100.00   Max.   :95.00   Max.   :87.00  
##                                                  
##  Max_Sea_Level_Pressure_In Mean_Sea_Level_Pressure_In
##  Min.   :29.47             Min.   :29.31             
##  1st Qu.:30.01             1st Qu.:29.93             
##  Median :30.12             Median :30.04             
##  Mean   :30.12             Mean   :30.03             
##  3rd Qu.:30.24             3rd Qu.:30.16             
##  Max.   :30.86             Max.   :30.81             
##                                                      
##  Min_Sea_Level_Pressure_In Max_Visibility_Miles Mean_Visibility_Miles
##  Min.   :29.14             Min.   : 3.00        Min.   : 1.00        
##  1st Qu.:29.84             1st Qu.:10.00        1st Qu.: 9.00        
##  Median :29.96             Median :10.00        Median :10.00        
##  Mean   :29.94             Mean   : 9.99        Mean   : 9.43        
##  3rd Qu.:30.08             3rd Qu.:10.00        3rd Qu.:10.00        
##  Max.   :30.75             Max.   :10.00        Max.   :10.00        
##                                                                      
##  Min_Visibility_Miles Max_Wind_Speed_MPH Mean_Wind_Speed_MPH
##  Min.   : 0.000       Min.   : 4.00      Min.   : 0.000     
##  1st Qu.: 4.000       1st Qu.: 8.00      1st Qu.: 3.000     
##  Median : 9.000       Median :10.00      Median : 4.000     
##  Mean   : 7.245       Mean   :11.09      Mean   : 4.631     
##  3rd Qu.:10.000       3rd Qu.:13.00      3rd Qu.: 6.000     
##  Max.   :10.000       Max.   :30.00      Max.   :23.000     
##                                                             
##  Max_Gust_Speed_MPH Precipitation_In       Events   
##  Length:689         Min.   :0.0000            :361  
##  Class :character   1st Qu.:0.0000   Fog      : 16  
##  Mode  :character   Median :0.0000   Fog-Rain : 13  
##                     Mean   :0.1051   Rain     :287  
##                     3rd Qu.:0.0900   Rain-Snow:  3  
##                     Max.   :2.2000   Rain-TS  :  7  
##                                      Snow     :  2</code></pre>
<p>Ok, so we have one NA for “Mean_Temperature_F”, “Max_Gust_Speed_MPH” seems to be represented as a character vector because it has “-” representing NA values, and we have 361 unlabelled Events.</p>
<p>Max Gust Speed should be the easiest one to fix, so we’ll start there.</p>
<pre class="r"><code>weather$Max_Gust_Speed_MPH &lt;- gsub(&quot;-&quot;, 0, weather$Max_Gust_Speed_MPH)

weather$Max_Gust_Speed_MPH &lt;- as.numeric(weather$Max_Gust_Speed_MPH)</code></pre>
<p>Great! We changed any absent values for Maximum Gust Speed to 0 MPH and changed the variable type to a number. Uh oh, looks like there are still 185 NA values for Max Gust Speed. That’s a lot to try to replace. I would normally suggest generating a model that could try to predict those values based on other known values, but for now, we’ll just leave it alone.</p>
<p>Since there is only one missing Mean Temperature, it seems the easiest way to fill in the hole is to look up what the average temperature was that day. <em>Note: I certainly would not recommend this if it were any more than one missing value</em></p>
<pre class="r"><code>weather[which(is.na(weather$Mean_Temperature_F)), 1]</code></pre>
<pre><code>## [1] &quot;2016-02-14&quot;</code></pre>
<p>Ok, so we’re looking for the Mean Temperature on February 14, 2016 in the zipcode 98101 (according to dataset documentation). Looks like the mean temperature that day was 50 degrees F.</p>
<p>Time to substitute in that value.</p>
<pre class="r"><code>weather[490, &quot;Mean_Temperature_F&quot;] &lt;- &quot;50&quot;</code></pre>
<p>Perfect. Now what to do with the unlabelled “Event” categories. The dataset “ReadMe” file from Pronto! doesn’t include any information about this weather dataset. The only thing I can think to do is refer to the Event as “Other”.</p>
<pre class="r"><code>weather$Events &lt;- gsub(&quot;^$&quot;, &quot;Other&quot;, weather$Events)
weather$Events &lt;- as.factor(weather$Events)</code></pre>
<p>Ok, we’re in good shape. Now to do a few quick visualizations.</p>
<div id="temperature" class="section level4">
<h4>Temperature</h4>
<div id="minimum" class="section level5">
<h5>Minimum</h5>
<div class="float">
<img src="unnamed-chunk-51-1.png" alt="Line graph showing fluctuating daily minimum temperatures in Seattle" />
<div class="figcaption">Line graph showing fluctuating daily minimum temperatures in Seattle</div>
</div>
</div>
<div id="mean" class="section level5">
<h5>Mean</h5>
<div class="float">
<img src="unnamed-chunk-52-1.png" alt="Line graph showing fluctuating daily mean temperatures in Seattle" />
<div class="figcaption">Line graph showing fluctuating daily mean temperatures in Seattle</div>
</div>
</div>
<div id="maximum" class="section level5">
<h5>Maximum</h5>
<div class="float">
<img src="unnamed-chunk-53-1.png" alt="Line graph showing fluctuating daily maximum temperatures in Seattle" />
<div class="figcaption">Line graph showing fluctuating daily maximum temperatures in Seattle</div>
</div>
</div>
</div>
<div id="events" class="section level4">
<h4>Events</h4>
<div class="float">
<img src="unnamed-chunk-54-1.png" alt="Bar graph showing that the most common weather events were rain and “other”" />
<div class="figcaption">Bar graph showing that the most common weather events were rain and “other”</div>
</div>
</div>
<div id="combining-weather-and-trip-datasets" class="section level4">
<h4>Combining Weather and Trip Datasets</h4>
<p>Good, so we can now see some parts of the weather data. Let’s combine the weather data with our trip data. Let’s try a <code>left join</code> from the <code>dplyr</code> package.</p>
<pre class="r"><code># Make a copy of the data frame
trip_3 &lt;- trip_2

# Change column name in trip_3 to match weather dataset
trip_3$Date &lt;- trip_3$start_date

# Left join the trip and weather dataframes by date.
trip_weather &lt;- left_join(trip_3, weather, by = &quot;Date&quot;)</code></pre>
</div>
<div id="mean-temperature-vs.-number-of-trips" class="section level4">
<h4>Mean Temperature vs. Number of Trips</h4>
<p>Ok. Now let’s see how the number of trips per day is influenced by weather (mean temperature, rounded to the nearest 5 degrees F)</p>
<div class="float">
<img src="unnamed-chunk-56-1.png" alt="Line graph showing that the number of trips peaks when temperatures are 60-70 degrees with higher or lower temperatures resulting in fewer rides." />
<div class="figcaption">Line graph showing that the number of trips peaks when temperatures are 60-70 degrees with higher or lower temperatures resulting in fewer rides.</div>
</div>
<p>So, as expected, there are more trips when the weather is mild but not too warm (over 70F) or too cold (below 50F). However, this figure may be influenced by the overall number of days that exhibited each mean temperature. Let’s try to standardize that.</p>
<div class="float">
<img src="unnamed-chunk-57-1.png" alt="Line graph showing that bike rides increased with an increase in temperature, relative to the number of days at each temperature." />
<div class="figcaption">Line graph showing that bike rides increased with an increase in temperature, relative to the number of days at each temperature.</div>
</div>
<p>So when we standardize our measurements, correcting for the number of days that actually reached each temperature, we see a steady increase in the number of trips until around 75F where the trend levels off. People are more likely to ride a bike when it’s warm outside.</p>
</div>
<div id="precipitation-vs.-number-of-trips" class="section level4">
<h4>Precipitation vs. Number of Trips</h4>
<p>If you’ve ever heard of Seattle, you probably hear that it rains all the time there. Let’s see if that has an impact on the number of trips taken in a day.</p>
<p>We’ll start with a figure standardized for number of days at a precipitation level, rounded to the nearest 0.2 inches.</p>
<div class="float">
<img src="unnamed-chunk-58-1.png" alt="Line graph showing that the number of trips dropped as the precipitation level increased." />
<div class="figcaption">Line graph showing that the number of trips dropped as the precipitation level increased.</div>
</div>
<p>Looks like even Seattleites have a limit when it comes to riding a bike in the rain. The more it rained, the fewer trips were taken per day.</p>
</div>
</div>
</div>
<div id="conclusions" class="section level2">
<h2>Conclusions</h2>
<p>So what did we learn from all of this? In the nearly 2 years since Pronto! opened in Seattle:</p>
<ul>
<li>236,065 bike trips were taken using this service</li>
<li>More trips occur in the spring and summer than winter/autumn</li>
<li>More trips occur during warm/dry weather</li>
<li>People tend to ride downhill more frequently than uphill</li>
<li>Pronto! bikes are used for work commutes during the week and more leisurely use on weekends</li>
<li>Short-Term Pass Holders are more likely to incur extra charges due to surpassing their time limit</li>
</ul>
<div id="suggestions-for-pronto" class="section level3">
<h3>Suggestions for Pronto!</h3>
<ul>
<li>Give users bonuses for bringing bikes back to a station on the top of the hill</li>
<li>Hold discounts in fall/winter</li>
<li>Find a way to alert short-term users that their time limit will be ending soon, and where the nearest station is to them at that time</li>
<li>Consider a 3rd membership option: “Commuter”. This may allow users to take bikes between 7-10 AM and 4-7 PM for free, but operate under a different time limit schedule during other times of day.</li>
</ul>
<p>As always, I appreciate any and all feedback from my work and appreciate you taking the time to see what I’ve done. Thanks!</p>
</div>
</div>

    </section>

    
    <div class='disqus'>
      <button class='disqus-show'><span class="show-message">Show Comments</span> <span class="inline-svg inline-svg-bubbles" >
<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="36" height="32" viewBox="0 0 36 32">
<title>bubbles3</title>
<path fill="currentColor" d="M34 28.161c0 1.422 0.813 2.653 2 3.256v0.498c-0.332 0.045-0.671 0.070-1.016 0.070-2.125 0-4.042-0.892-5.398-2.321-0.819 0.218-1.688 0.336-2.587 0.336-4.971 0-9-3.582-9-8s4.029-8 9-8c4.971 0 9 3.582 9 8 0 1.73-0.618 3.331-1.667 4.64-0.213 0.463-0.333 0.979-0.333 1.522zM7.209 6.912c-2.069 1.681-3.209 3.843-3.209 6.088 0 1.259 0.35 2.481 1.039 3.63 0.711 1.185 1.781 2.268 3.093 3.133 0.949 0.625 1.587 1.623 1.755 2.747 0.056 0.375 0.091 0.753 0.105 1.129 0.233-0.194 0.461-0.401 0.684-0.624 0.755-0.755 1.774-1.172 2.828-1.172 0.168 0 0.336 0.011 0.505 0.032 0.655 0.083 1.323 0.125 1.987 0.126v4c-0.848-0-1.68-0.054-2.492-0.158-3.437 3.437-7.539 4.053-11.505 4.144v-0.841c2.142-1.049 4-2.961 4-5.145 0-0.305-0.024-0.604-0.068-0.897-3.619-2.383-5.932-6.024-5.932-10.103 0-7.18 7.163-13 16-13 8.702 0 15.781 5.644 15.995 12.672-1.284-0.572-2.683-0.919-4.133-1.018-0.36-1.752-1.419-3.401-3.070-4.742-1.104-0.897-2.404-1.606-3.863-2.108-1.553-0.534-3.211-0.804-4.928-0.804s-3.375 0.271-4.928 0.804c-1.46 0.502-2.76 1.211-3.863 2.108z"></path>
</svg>

</span>
</button>
      <div class='disqus-comments' hidden>
        
      </div>
    </div>
    
  </article>

</main>
<footer class='footer__single'>
  
  <div class='footer__content'>
    <div class="footer-buttons">
      
  

  
    <a href="mailto:ahmed.azeez1987@gmail.com" class="social-button email" aria-label="Find me on email">
      <span class="inline-svg inline-svg-email" >
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M464 0H48C21.49 0 0 21.49 0 48V336C0 362.51 21.49 384 48 384H464C490.51 384 512 362.51 512 336V48C512 21.49 490.51 0 464 0ZM464 48V88.805C441.578 107.064 405.832 135.456 329.413 195.295C312.572 208.542 279.212 240.367 256 239.996C232.792 240.371 199.421 208.537 182.587 195.295C106.18 135.465 70.425 107.067 48 88.805V48H464Z"/></svg>

</span>

    </a>
  

  

  
    <a href="https://github.com/mscazmy" class="social-button github" aria-label="Find me on github">
      <span class="inline-svg inline-svg-github" >
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><path fill="currentColor" d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"/></svg>

</span>

    </a>
  

  

  

  
    <a href="https://www.linkedin.com/in/ahmed-a-hasan" class="social-button linkedin" aria-label="Find me on linkedin">
      <span class="inline-svg inline-svg-linkedin" >
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448.1 512"><path fill="currentColor" d="M100.3 448H7.4V148.9h92.9V448zM53.8 108.1C24.1 108.1 0 83.5 0 53.8S24.1 0 53.8 0s53.8 24.1 53.8 53.8-24.1 54.3-53.8 54.3zM448 448h-92.7V302.4c0-34.7-.7-79.2-48.3-79.2-48.3 0-55.7 37.7-55.7 76.7V448h-92.8V148.9h89.1v40.8h1.3c12.4-23.5 42.7-48.3 87.9-48.3 94 0 111.3 61.9 111.3 142.3V448h-.1z"/></svg>

</span>

    </a>
  

  

  

  

  

  

  


    </div>
  </div>

  <div class='footer-more'>
    <a href="/about">About</a><a href='/contact'>Contact</a>
  </div>

  <div class='credits'>
    <div class='credits-people'>
      <p>Code by <a href='http://amber.rbind.io'>Amber Thomas</a></a></p>
    </div>
    <div class='credits-location'>
      <p>Modified by <a href='ahmed.azeez1987@gmail.com'>Ahmed Azeez</a></a></p>
    </div>


  </div>




  
  
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js"></script>
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/r.min.js"></script>
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/yaml.min.js"></script>
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/javascript.min.js"></script>
  
  <script>
    hljs.initHighlightingOnLoad();
  </script>



  <script src="https://mscazmy.github.io/js/theme.js"></script>

</footer>
